on: [push, pull_request]

name: CI

jobs:
  CI:
    name: Node 22 and pnpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript type checking
        run: pnpm exec tsc --noEmit

      - name: Run ESLint
        run: pnpm run lint

      - name: Validate Prisma
        run: pnpm exec prisma generate && pnpm exec prisma validate

      - name: Build application
        run: pnpm run build
